# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(),
        ),
    ]
