# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 20:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_auto_20161103_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField()),
                ('file_up', models.FileField(blank=True, upload_to=b'')),
                ('url', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='picture', unique=True)),
            ],
        ),
    ]
